### ISSUE TITLE
Installing a profile server: Missing Directories?

### ISSUE THREAD

**Issue by headygains** [Fermat-ORG/iop-profile-server#33]
I'm attempting to setup a docker container running a IoP Profile Server yet it seems that according to your installation instructions I don't have all the files required to do this? I may just be missing other src files that aren't located int the iop-profile-server repo.  My issue is I'm missing 2 of the 3 directories mentioned [in the installation instructions here.](
https://github.com/Fermat-ORG/iop-profile-server/blob/master/docs/INSTALLATION.md#build-profile-server)

**Comment by dejfcz** [comment]
Could you please be more specific?
And also, are you working with the release, not the master branch source code?
Also, could you not use the binary release?

**Comment by dejfcz** [comment]
The installation instructions have been updated to explicitly mention that it is the release branch that should always be used by anyone other than devs. This should fix all the confusion.
